# [YAML语言教程](https://www.ruanyifeng.com/blog/2016/07/yaml.html)

# ==================================================
#             服务器是否开启强制白名单
# ==================================================
force_whitelist: true

# 命令提示字符, 可修改为与应用场景不冲突的字符，例如: /
cmd_prompt_char: '$'

# ==================================================
#     IP地址拦截白名单，在列表区域中的IP被允许登录服务器
# ==================================================
allow_country_code:
#  - CN
#  - JP
#  - TW